config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'books#index'
  resources :books do
    resources :book_borrows, only: :create
  end

  resources :magazines

  namespace :api do
    namespace :v1 do
      resources :books
      resources :magazines
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  CREATE_PARAMS = %i(title desc quantity)

  validates :borrowed, numericality: { less_than_or_equal_to: :quantity, allow_blank: true }
  validates :borrowed, :quantity, numericality: { only_integer: true, allow_blank: true }

  scope :available_books, ->{Books::AvailableBookQuery.run}
end

app/models/magazine.rb
class Magazine < ApplicationRecord
  CREATE_PARAMS = %i(title desc quantity)

  validates :borrowed, numericality: { less_than_or_equal_to: :quantity, allow_blank: true }
  validates :borrowed, :quantity, numericality: { only_integer: true, allow_blank: true }
end

app/models/user.rb
class User < ApplicationRecord
  has_one :bank_account
end

app/controllers/api/api_base_controller.rb
class Api::ApiBaseController < ApplicationController
  protect_from_forgery with: :null_session

  def render_json(object, args = nil)
    if args.nil?
      render json: object
    else
      render json: object, **args
    end
  end
end

app/controllers/api/v1/books_controller.rb
class Api::V1::BooksController < Api::ApiBaseController
  def index
    books = Book.all.decorate

    render_json books, each_serializer: Api::V1::BookSerializer
  end

  def show
    book = Book.first.decorate

    render_json book, serializer: Api::V1::BookSerializer
  end
end

app/controllers/api/v1/magazines_controller.rb
class Api::V1::MagazinesController < Api::ApiBaseController
  def index
    magazines = BookDecorator.decorate_collection Magazine.all

    render_json magazines, each_serializer: Api::V1::MagazineSerializer
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/book_borrows_controller.rb
class BookBorrowsController < ApplicationController
  def create
    book = Book.find_by id: params[:book_id]
    book.update! borrowed: book.borrowed.to_i + 1 if book.present?

    redirect_to books_url
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.available_books.decorate
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.create! book_params

    redirect_to action: :index
  end

  private

  def book_params
    params.require(:book).permit Book::CREATE_PARAMS
  end
end

app/controllers/magazines_controller.rb
class MagazinesController < ApplicationController
  def index
    @magazines = BookDecorator.decorate_collection Magazine.all
  end

  def new
    @magazine = Magazine.new
  end

  def create
    @magazine = Magazine.create! magazine_params

    redirect_to action: :index
  end

  private

  def magazine_params
    params.require(:magazine).permit Magazine::CREATE_PARAMS
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_helper.rb
module BookHelper
  def available_book(book)
    book_borrowed = book.borrowed.present? ? book.borrowed : 0

    book.quantity - book_borrowed
  end
end

app/views/books/_book.html.erb
<tr>
  <td class="col-md-2"><%= book.title %></td>
  <td class="col-md-2"><%= book.desc %></td>
  <td class="col-md-2"><%= book.available %></td>
  <td class="col-md-2">
    <%= link_to 'Borrow', book_book_borrows_path(book), method: :post %>
  </td>
</tr>

app/views/books/index.html.erb
<h1>Book list</h1>

<%= link_to 'Create', new_book_path %>
<% if @books.present? %>
  <table>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Available</th>
      <th></th>
    <tr>
    <%= render @books %>
  </table>
<% else %>
  <p>No book available</p>
<% end %>

app/views/books/new.html.erb
<%= form_with model: @book do |f| %>
  <%= f.label :title, 'Title' %>
  <%= f.text_field :title, autofocus: true %>

  <%= f.label :desc, 'Description' %>
  <%= f.text_field :desc %>

  <%= f.label :quantity, 'Quantity' %>
  <%= f.number_field :quantity %>

  <%= f.submit 'Submit', class: "btn btn-primary btn-right" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DesignPattern</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <br>
    <%= yield %>
  </body>
</html>

app/views/magazines/_magazine.html.erb
<tr>
  <td class="col-md-2"><%= magazine.title %></td>
  <td class="col-md-2"><%= magazine.desc %></td>
  <td class="col-md-2"><%= magazine.available %></td>
</tr>

app/views/magazines/index.html.erb
<h1>Magazine list</h1>

<%= link_to 'Create', new_magazine_path %>
<% if @magazines.present? %>
  <table>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Available</th>
      <th></th>
    <tr>
    <%= render @magazines %>
  </table>
<% else %>
  <p>No magazine available</p>
<% end %>

app/views/magazines/new.html.erb
<%= form_with model: @magazine do |f| %>
  <%= f.label :title, 'Title' %>
  <%= f.text_field :title, autofocus: true %>

  <%= f.label :desc, 'Description' %>
  <%= f.text_field :desc %>

  <%= f.label :quantity, 'Quantity' %>
  <%= f.number_field :quantity %>

  <%= f.submit 'Submit', class: "btn btn-primary btn-right" %>
<% end %>